### PR TITLE
fix: dynamic year for copyright in footer

### LINKED ISSUE #2324: [Bug]: Make copyright year dynamic.
### 👀 Is there an existing issue for this?

- [X] I have searched and didn't find similar issue

### 👍 Current behavior

The copyright year is static and does not update automatically. I want to work on this issue assign me
image

### 👟 Steps to Replicate

Open the website and check the footer for the static copyright year.

### 🧱 Your Environment

_No response_

### 💻 Operating system

Windows

### 🎲 Version

I am using latest version

### 💻 Repository

website

### PR DESCRIPTION
**Pull request by techmannih**
Close https://github.com/keploy/keploy/issues/2324
Issue https://github.com/keploy/keploy/issues/2324

@khareyash05 please review this PR and merge it at your convenience.

NOW
image

 BEFORE
 
image

### CODE REVIEW

**Review by khareyash05 — COMMENTED** [review]
Could you please revert the package lock changes, it could cause unecessary issues with other PR's

**Comment by techmannih** [comment]
@khareyash05 please check now

**Review by khareyash05 — APPROVED** [review]
LGTM!

**Comment by techmannih** [comment]
@Swpn0neel  @khareyash05  why is not updated in deployed link please check once

**Comment by khareyash05** [comment]
@techmannih it will be released later with other changes. Thanks

**Comment by techmannih** [comment]
@khareyash05 Okay got it thanks sir

**Pull request merged**
