### PR TITLE
adding particle in background of hero section

### PR DESCRIPTION
**Pull request by Neeraj-gagat**
Added particles in hero section background

This feature request was open on [https://github.com/https://github.com/keploy/keploy/issues/2162] by @nehagup 
To add magic-ui particles in the background of hero section

fixes #2162
before 
[Screencast from 07-08-24 07:44:08 PM IST.webm](https://github.com/user-attachments/assets/27b4cf2b-78d0-4ef8-aeb8-ae2c72c2178d)

after 
[Screencast from 07-08-24 07:46:20 PM IST.webm](https://github.com/user-attachments/assets/42e85591-9c57-4b8e-a4a8-08fe32c6041d)

### CODE REVIEW

**Comment by Neeraj-gagat** [comment]
@nehagup review required!

**Review by nehagup — COMMENTED** [review]
Hi @Neeraj-gagat thanks for the PR, this helps. However, how about we - 
- make the particles lighter and in gradient orange and brown, you can refer to the theme in readme or tailwind.css. 
- Restrict the area of particle to just the preview video image background in the hero section. 

Please note that this is an experimenal integration to understand if this will look good.

**Comment by Neeraj-gagat** [comment]
Hi @nehagup  
     
what did you mean by lighter did you mean small or lighter in just colour .
and do you want particles in both [orange , brown ]colour .

**Comment by nehagup** [comment]
Hi @Neeraj-gagat sorry I missed the notification for this. 
> what did you mean by lighter did you mean small or lighter in just colour .
By lighter I meant both smaller and lower opacity. 

> and do you want particles in both [orange , brown ]colour .
You can try with a mix and see how it goes? that's more on experimental side.

**Comment by Neeraj-gagat** [comment]
hi @nehagup  sorry for responding late 
can you please check it out 
[Screencast from 02-09-24 07:59:47 PM IST.webm](https://github.com/user-attachments/assets/aa64c0e3-68cf-4fa9-b648-c6232e130210)

**Comment by nehagup** [comment]
Hi @Neeraj-gagat looks better in the video, please push the changes for code-review with resolved conflicts.

**Comment by Neeraj-gagat** [comment]
Hi @nehagup  I have made the updates to my PR based on your feedback and resolved the conflicts, could you please review the code and let me know if it needs anymore further chnages.

**Review by nehagup — APPROVED** [review]
This looks very nice! Thanks @Neeraj-gagat 👏

**Pull request merged**
