### PR TITLE
resolving errors

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the Building errors because of LottiePlayer:

image

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup i'll attach the screenshot:
Screenshot from 2024-04-03 10-59-04

**Comment by Hermione2408** [comment]
> Fixes the Building errors because of LottiePlayer:
> 
> image

@Aditya-eddy In which node version are you getting these errors, I tried building the main branch in node 18 didn't get any error

**Comment by Aditya-eddy** [comment]
Basically this error is caused by node>18. I am using node v-20.
Its because of the Lottie player.
[Ref](https://github.com/Gamote/lottie-react/issues/101)

**Comment by Hermione2408** [comment]
> Basically this error is caused by node>18. I am using node v-20. Its because of the Lottie player. [Ref](https://github.com/Gamote/lottie-react/issues/101)

Got it!

**Review by Hermione2408 — APPROVED** [review]
LGTM! @nehagup

**Review by nehagup — APPROVED** [review]

**Pull request merged**
