### PR TITLE
fix/overlapping items

### LINKED ISSUE #1698: [bug]: TestResult summary overlap issue at certain media sizes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On a certain media size(width 768-1005px), the TestResult summary overlap with other components on the page.  I expect the summary to be clearly visible and not obscured by any other elements on the page, regardless of the media size or screen resolution.

### Steps to reproduce

a. Adjust the browser to a specific media size (width 768-1005px).
b. Navigate to the home page where the TestResult summary is displayed.
c. Observe that the summary is overlapping with other components on the page.image

### Environment

None

### Version

Cloud

### Repository

website

### PR DESCRIPTION
**Pull request by ethanwater**
Fixes: keploy/keploy#1698

Super simple. All I did was remove the 'md:max-w-none' property to prevent item overlapping. It's worth noting that it seems a segment of the transition system may be a bit off due to a difference between initial height and post-leave height. However, this specific issue has been fixed.

### CODE REVIEW

**Comment by Hermione2408** [comment]
Hey @ethanwater there is conflict in your PR please resolve it

**Comment by ethanwater** [comment]
@Hermione2408 Conflicts resolved.

**Comment by Hermione2408** [comment]
Screenshot from 2024-03-29 00-09-47
Hey @ethanwater please check it, not able to run locally

**Comment by ethanwater** [comment]
Ah, this is because of formatting errors post conflict revisions. I can just fmt to fix this. Or manually remove the spaces. Silly conflicts.

**Comment by ethanwater** [comment]
@Hermione2408 The native integration image has been replaced? Are these changes even necessary anymore. This issue can probably be closed. Moving on.

**Comment by Hermione2408** [comment]
> @Hermione2408 The native integration image has been replaced? Are these changes even necessary anymore. This issue can probably be closed. Moving on.

Hey @ethanwater this issue persists on medium and small screen size 
Screenshot from 2024-03-31 13-25-17

**Comment by ethanwater** [comment]
@Hermione2408 The version you sent me is outdated since #4 , as you can see here: https://keploy.io.  But as I said before, the code I submitted for the original version works as you can see below. 

However since #4 , this PR and the image you provided is outdated by 4 days. Unless we plan to use the original style (the style you show in the image you just sent), then this PR can be closed. If not, then it can be merged.

I would also like to mention that I like the changes @sahadat-sk made in his PR towards the look and feel of the section in question.

**My Changes (Pre PR #4 ):**
Screenshot 2024-03-31 at 07 09 38
Screenshot 2024-03-31 at 07 20 16
Screenshot 2024-03-31 at 07 09 45



**Actual Public Keploy.io Site (Post PR #4 ):**
Screenshot 2024-03-31 at 07 14 27

Either way, if you would like to test this branch, then it has been updated for you to do so.

**Review by nehagup — COMMENTED** [review]
@ethanwater thanks for the initiative! This is needs to be resolved for the md and sm screen size where there's old layout of features, which looks to be solved in this PR. However, for larger screen sizes, please revert back the layout to what @sahadat-sk implemented :)

**Comment by ethanwater** [comment]
@nehagup anytime! I just updated the code to ensure there is no overlapping for the native integration image, while maintaining the layout @sahadat-sk made.

**Review by nehagup — APPROVED** [review]
Thanks @ethanwater ! LGTM! 👏

**Pull request merged**
