### PR TITLE
Created "Platform" section in Keploy's Navbar

### LINKED ISSUE #2068: [feature]: revamp the navbar on keploy landing page
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Currently the navbar has below fields:- 
image

The new navbar should have below tabs and structure
image

### Why should this be worked on?

Since now keploy has different pillar pages and resources it would be good to have proper structure so first time visitor or even regular visitor can easily navigate to page or resource they are looking for.

### Repository

website

### PR DESCRIPTION
**Pull request by yaten2302**
# Fixes https://github.com/keploy/keploy/issues/2068

# Screenshots

image

image

### CODE REVIEW

**Review by Aditya-eddy — CHANGES_REQUESTED** [review]
Hey @yaten2302 thanks for the pr couple changes that i could suggest:
1. The line that appears below the platform should also be of the primary pallte.
2. The stuff inside the navbar should also follow the max-width of the website or there must be some extra stuff added so that it looks full.
3. The background should be same as the navbar background-color and there should be some shadow added.
4. Also please center the middle section of the navbar.
5. The text color changes as we hover should be in Primary pallete. But please experiment on it.
Thanks!!

**Comment by yaten2302** [comment]
Hey @Aditya-eddy , thanks for the suggestions, actually, I've a few doubts, could you please guide me with those:
1. As you told that the line below the Platform heading, so should it be of the same color as that of the dropDown? Actually, I got confused that are you talking of about the color of the line or something else?
2. For the stuff inside the dropDown, should it be like stretched across the whole dropdown or should i center it? because ig it's already in the center and i've justified it evenly - `justify-evenly`.
4. Should I center the "Solutions" section?
5. So, on hover on let's say - "What is Keploy?", the text color should change to orange type? (as it was earlier?)

**Comment by Aditya-eddy** [comment]
> Hey @Aditya-eddy , thanks for the suggestions, actually, I've a few doubts, could you please guide me with those:
> 
> 1. As you told that the line below the Platform heading, so should it be of the same color as that of the dropDown? Actually, I got confused that are you talking of about the color of the line or something else?
> 2. For the stuff inside the dropDown, should it be like stretched across the whole dropdown or should i center it? because ig it's already in the center and i've justified it evenly - `justify-evenly`.
> 3. Should I center the "Solutions" section?
> 4. So, on hover on let's say - "What is Keploy?", the text color should change to orange type? (as it was earlier?)

1.It should be from the primary pallete.
2.Currently we don't have a lot of stuff so have a max-width same as website.
3.It's already in the center. I was talking about the top navbar it's tilted to a little right now.
4.Yes let's try from the primary pallete.

**Comment by yaten2302** [comment]
1. Ok, so the color of the line under Platform, it should contain a color form the primary pallete, am I right?
2. Got this point 👍 
3. Oh, about the top navbar, actually, 1 or 2 more dropdowns will be added and then it'll automatically be in the center, rn it's towards right. 
4. Got this point 👍 .

Thanks for the suggestions, I'll make the changes ASAP 👍

**Comment by yaten2302** [comment]
@Aditya-eddy , actually, I tried changing the color of the underline below the Platform, but ig it's too light? This color is same as navbar bg. <br>
image

**Comment by yaten2302** [comment]
@Aditya-eddy , I've pushed the changes, kindly review.

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 :
1. Primary pallete is actually the orange one. The underline should become orange like when we hover over docs.
2. Also the background color of the box when it opens is not as the same color as navbar and also shadow is not visible on the box.

**Comment by PranavBarthwal** [comment]
> @Aditya-eddy , I've pushed the changes, kindly review.

@yaten2302 should we wait for our sections until this PR is corrected? Or can I help you with something in platform section till then?

**Comment by yaten2302** [comment]
@PranavBarthwal , you don't need to wait for this PR and for the Platform section, only minor changes are left, which I'll make (not difficult at all), you can fork my repo and add your code their and the commits will be shown here automatically.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal , you don't need to wait for this PR and for the Platform section, only minor changes are left, which I'll make (not difficult at all), you can fork my repo and add your code their and the commits will be shown here automatically.

For my commits to show here I must push my changes in the main branch only, right?

I was about to create a new branch!

**Comment by yaten2302** [comment]
Yes, you've to push your changes in the main branch only, and also, you've to work on the fork, which I sent in the discussions for this issue. If you'll fork the main repo of keploy's website, then there'll be 2 3 PRs, which is not required.

**Comment by PranavBarthwal** [comment]
> Yes, you've to push your changes in the main branch only, and also, you've to work on the fork, which I sent in the discussions for this issue. If you'll fork the main repo of keploy's website, then there'll be 2 3 PRs, which is not required. 

yeah yeah, I'm working on your fork only, will push changes tonight.

**Comment by yaten2302** [comment]
@Aditya-eddy , could you please check that are these changes good <br>
image

**Comment by yaten2302** [comment]
@vaishnavi192 , could you also please confirm that are you working on this issue? You were assigned the "Blogs" section if I'm not wrong?

**Comment by yaten2302** [comment]
@PranavBarthwal , since vaishnavi192 is not active, then should we both divide the work for the blogs section?

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal , since vaishnavi192 is not active, then should we both divide the work for the blogs section? 

Yeah sure.

**Comment by yaten2302** [comment]
@PranavBarthwal , what's the update on the "About" seciton? Have you completed it?
And for the Blogs part, I'll edit the `navItemWithSmallDropdown.tsx` and then you can add the links to it 👍

**Comment by yaten2302** [comment]
Also, @Aditya-eddy , @Sonichigo , @Swpn0neel sir, could you please guide that for the "Platform" part, some of the icons are same, so instead of those, with which icons should I replace it with? Actually, I wasn't able to find some relatable icons, that's why I asked

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal , what's the update on the "About" seciton? Have you completed it?
> And for the Blogs part, I'll edit the `navItemWithSmallDropdown.tsx` and then you can add the links to it 👍 

Okay, we can work this way👍

**Comment by Sonichigo** [comment]
> Also, @Aditya-eddy , @Sonichigo , @Swpn0neel sir, could you please guide that for the "Platform" part, some of the icons are same, so instead of those, with which icons should I replace it with? Actually, I wasn't able to find some relatable icons, that's why I asked

for now you can use lottifiles.com for the assests. Also, socials should be below the product and solution as in solutions aspect there will me many more pages to be added.

**Comment by yaten2302** [comment]
Sure, @Sonichigo sir, I'll make the changes 👍

**Comment by yaten2302** [comment]
@Sonichigo sir, actually, I was trying to search for the icons on lottifiles, but ig they provide animations instead of svgs or something? Do we need animations for the navbar?

**Comment by Sonichigo** [comment]
> @Sonichigo sir, actually, I was trying to search for the icons on lottifiles, but ig they provide animations instead of svgs or something? Do we need animations for the navbar?

For Solution's icon, you can take genric icons related the heading. It's available on https://icon-icons.com/

**Comment by yaten2302** [comment]
@Sonichigo sir, I've made the changes and also added the "Blogs" page, could you please review. Here are some screenshots of the changes <br>
image
<br>
image
<br>
image

**Comment by PranavBarthwal** [comment]
> @Sonichigo sir, I've made the changes and also added the "Blogs" page, could you please review. Here are some screenshots of the changes <br>
> image
> <br>
> image
> <br>
> image
> 

Please give a look at my PR in your repo

**Comment by yaten2302** [comment]
@PranavBarthwal , I've commented on your PR 👍

**Comment by yaten2302** [comment]
@Sonichigo, sir, could you please share the links for the about section so that @PranavBarthwal can work on it

**Comment by Sonichigo** [comment]
About section links are not yet live, for now you can add one link there 

- https://keploy.io/careers which can be made live soon! 

@yaten2302 @PranavBarthwal please add the points for this and other pr here https://github.com/keploy/.github/tree/main/kroc'24

**Comment by PranavBarthwal** [comment]
> About section links are not yet live, for now you can add one link there 
> 
> - https://keploy.io/careers which can be made live soon! 
> 
> @yaten2302 @PranavBarthwal please add the points for this and other pr here https://github.com/keploy/.github/tree/main/kroc'24

Okay 👍

**Comment by yaten2302** [comment]
Made the changes @Sonichigo sir 👍 
Also, @PranavBarthwal , can you add the careers page to the About section? (using the `navItemWithSmalldropDown.tsx`)
Ig you need to change the width and height a little bit, you can do that by creating another file.

**Pull request closed without merging**
