### PR TITLE
To correct github star numbers

### PR DESCRIPTION
**Pull request by sk0618054**
Solve the error of Star us on github button [#1670 
](https://github.com/keploy/keploy/issues/1670)  Now it works on the real time data.Screenshot 2024-03-10 191730

### CODE REVIEW

**Review by nehagup — CHANGES_REQUESTED** [review]
@sk0618054 ! appreciate the effort, however, the effect of increasing number count has gone with this change.

**Comment by nehagup** [comment]
@sk0618054 are you still working on this?

**Comment by sk0618054** [comment]
yes @nehagup but I’m being unable to debug this..

**Comment by sk0618054** [comment]
@nehagup please check it now it works .https://github.com/keploy/website/pull/2/commits/faf3166bd4303ffbf400877c1b42d550e853f424

https://github.com/keploy/website/assets/139760052/e458e2eb-d311-4795-8528-edc7a2297a0a

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @sk0618054 
- The star number is not getting updated correctly in mobile view please check.
- Please revert back linting changes it can create conflicts.
[Screencast from 27-03-24 03:02:33 PM IST.webm](https://github.com/keploy/website/assets/78696767/23cc8643-169e-402c-add7-55104b0e5aec)

**Comment by nehagup** [comment]
@sk0618054  closing this PR as it's inactive. Please feel free to re-open once you make progress.

**Pull request closed without merging**
