### PR TITLE
Fixed responsiveness issue in medium screen

### PR DESCRIPTION
**Pull request by Swpn0neel**
Fixed an issue with the responsiveness of the features section of Keploy's website, where there was a content overlap for the medium screens.

Fixes issue: [#1843](https://github.com/keploy/keploy/issues/1843)

*Previously, it looked like this:* <br>
image <br>
*Currently, after fixing, it looks like this:* <br>
image

### CODE REVIEW

**Review by nehagup — COMMENTED** [review]
Still breaking for me. also please remove the linting changes to keep the PR clean. 

Screenshot 2024-06-03 at 5 37 53 PM

**Comment by Swpn0neel** [comment]
Can you tell me the device name in which it's breaking? @nehagup

**Comment by nehagup** [comment]
> Can you tell me the device name in which it's breaking? @nehagup

I checked for iPad Air

**Comment by Swpn0neel** [comment]
Strange, because it's working perfectly for me 😕 I just re-checked it right now...
image

**Comment by Swpn0neel** [comment]
I've reverted the applied lints!

**Review by nehagup — APPROVED** [review]

**Pull request merged**
