### PR TITLE
added sticky navbar for VS Code Extention

### PR DESCRIPTION
**Pull request by ab7022**
Added a responsive, sticky banner promoting the VS Code extension on the website's landing page for enhanced visibility.
scrnli_vDKax2j3SJxC4P

### CODE REVIEW

**Comment by ab7022** [comment]
This PR adds an attractive sticky for the VS Code Extension. 

Closes [keploy/website#2383](https://github.com/keploy/keploy/issues/2383) - Add Attractive sticky for VS Code Extension.

**Comment by ab7022** [comment]
moved Vs code Navbar to the top
Closes [keploy/website#2383](https://github.com/keploy/keploy/issues/2383) -scrnli_VzUxJux5Xz8bey
closes #120

**Comment by TvisharajiK** [comment]
Hey @ab7022 This looks good, can you add some shadow to it?

**Comment by ab7022** [comment]
hey @TvisharajiK i have added some shadows.
keploy added shadow

**Comment by khareyash05** [comment]
Hi @ab7022, Nice work! Could you please attach screenshots for mobile view as well, will make merging it easier

**Comment by ab7022** [comment]
Hey @khareyash05 , i have added responsiveness for mobile screens while maintaining the same design for desktop view.

### for desktop:
keploy added shadow

### for mobile screens: 
mobile_responsive

**Comment by ab7022** [comment]
hey @khareyash05 @TvisharajiK it's ready for review.

**Review by khareyash05 — APPROVED** [review]

**Comment by khareyash05** [comment]
Hey @ab7022 , could you please dm on the slack, would like to discuss a few things with you.

**Comment by ab7022** [comment]
@khareyash05 yeah sure, can you send me the link?

**Comment by khareyash05** [comment]
https://join.slack.com/t/keploy/shared_invite/zt-2tzkoz6vb-WpY_ebmnTV5oqH29KprKkA
, I go by the same name

**Pull request merged**
