### PR TITLE
added FAQs to Keploy's /unit-test-generator route

### PR DESCRIPTION
**Pull request by yaten2302**
# About

Fixes - https://github.com/keploy/keploy/issues/2095

This PR adds a new FAQ to the `/unit-test-generator` route.

### CODE REVIEW

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Please update the name of the PR, and send me a screenshot of the modified site from your localhost

**Comment by yaten2302** [comment]
@Swpn0neel sir, here's a screenshot of the changes: <br>
image

**Comment by Swpn0neel** [comment]
> @Swpn0neel sir, here's a screenshot of the changes: <br>
> image
> 

Put it under UTG, it should be the 2nd question!

**Comment by yaten2302** [comment]
Made the changes @Swpn0neel sir 👍

**Review by Swpn0neel — APPROVED** [review]
LGTM!

**Review by Aditya-eddy — APPROVED** [review]
LGTM!!

**Pull request merged**
