### PR TITLE
[feature]: Added style to"star on github" button on landing page

### PR DESCRIPTION
**Pull request by akshat99812**
# PR Description: Add Hover Effects and Sliding Animation to GitHub Link Component

## Summary
This PR enhances the GitHub link component within the project by adding a set of visual and interactive effects, including hover effects, animations, and a sliding white highlight. These changes aim to improve the user experience by making the link more visually appealing and interactive.

## Related Issues
- Addresses #2235 (Link to the issue)

## Screenshots/Video

https://github.com/user-attachments/assets/94f0c1e9-56bd-40f4-b71d-8adb66f81516

### CODE REVIEW

**Comment by akshat99812** [comment]
hey @nehagup could you please review the pr

**Review by nehagup — COMMENTED** [review]
Thanks for the PR @akshat99812 ! Here are a few suggestions: 
- can you please same change in mobile menu bar as well?
- by default the star button should be filled, on hover it should have shadow which will make it "shine on hover".
- On-hover there's a blue border I see around the button which is looking out of the place. 

Please lmk if you have any questions.

**Comment by akshat99812** [comment]
@nehagup I've made the updates to my PR based on your feedback. When you have a moment, could you please review the changes and let me know if there's anything else that needs adjustment? 

https://github.com/user-attachments/assets/936b9ac8-cafb-40cb-baf4-ba326044b572

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
thanks for the PR @akshat99812 !

**Pull request merged**
