### PR TITLE
fix: changes banner for gittogether page w/signoff

### PR DESCRIPTION
**Pull request by chintanpuggalok**
changes the page for gittother with the given image

### CODE REVIEW

**Comment by chintanpuggalok** [comment]
Fixes keploy/keploy#1866

**Comment by Hermione2408** [comment]
Hey @chintanpuggalok thanks for making PR, but instead of replacing the whole background only gittogether image should be replaced with the following image

**Comment by chintanpuggalok** [comment]
@Hermione2408 

is this better?

**Comment by chintanpuggalok** [comment]
@Hermione2408 is this better
image

**Comment by Sonichigo** [comment]
Hey @chintanpuggalok , the banner is not aligned properly yet. We have a video in the background then above the logo of the event, the image would replace both of them so it's center aligned.

image

This part needs to be changed as a whole 
cc: - @Hermione2408

**Comment by nehagup** [comment]
@chintanpuggalok still working on this?

**Comment by chintanpuggalok** [comment]
let me try

**Comment by chintanpuggalok** [comment]
Does this seem okay?
image

**Comment by Sonichigo** [comment]
> Hey @chintanpuggalok , the banner is not aligned properly yet. We have a video in the background then above the logo of the event, the image would replace both of them so it's center aligned.
> 
> image
> This part needs to be changed as a whole cc: - @Hermione2408

hey @chintanpuggalok i have already mentioned the acceptable solution above. Please refer to this.

**Comment by nehagup** [comment]
Closing this since it's stale. Please feel free to reopen.

**Pull request closed without merging**
