### PR TITLE
feat: create a case studies page

### PR DESCRIPTION
**Pull request by Om-Thorat**
ref: [#2385](https://github.com/keploy/keploy/issues/2385)

### Created a new responsive case studies page. Here is an attached demo video :

https://github.com/user-attachments/assets/e3046983-f95f-4209-89e1-392530845b2b

Do Let me know if any tweaks are required !

### CODE REVIEW

**Comment by Om-Thorat** [comment]
image


added functional Search and demo Tags

**Comment by TvisharajiK** [comment]
@Om-Thorat hey, this looks good
1. Can you change the blue color of the tags that you are using - Maruti Suzuki, TAT one 
2. Latest Case study by Keploy - Can you try a different color for that from the brand, it is a little bit too dark

**Comment by Om-Thorat** [comment]
> @Om-Thorat hey, this looks good
> 
>     1. Can you change the blue color of the tags that you are using - Maruti Suzuki, TAT one
> 
>     2. Latest Case study by Keploy - Can you try a different color for that from the brand, it is a little bit too dark

image

image


do these seem any better? do let me know :)

**Comment by TvisharajiK** [comment]
Screenshot 2024-11-05 at 5 06 25 PM

Reduce the space between the case studies paragraph and the case studies blobs

the rest looks gtg

**Comment by Om-Thorat** [comment]
> Reduce the space between the case studies paragraph and the case studies blobs
> 
> the rest looks gtg

image

:D looks much better now

**Comment by khareyash05** [comment]
Hey @Om-Thorat , could you please attach screenshots for mobile version?Thanks

**Comment by Om-Thorat** [comment]
> Hey @Om-Thorat , could you please attach screenshots for mobile version?Thanks

Screenshot From 2024-11-09 23-43-25

Screenshot From 2024-11-09 23-43-04


here you go!

**Review by khareyash05 — APPROVED** [review]

**Comment by khareyash05** [comment]
Nice work! @Om-Thorat , could you please dm on slack, would like to discuss a few details, thanks

**Pull request merged**
