### PR TITLE
feature: navbar dock

### PR DESCRIPTION
**Pull request by sakethreddy21**
if the user at the top 
image

if the user at  !top
Screenshot 2024-10-29 015106

### CODE REVIEW

**Comment by sakethreddy21** [comment]
Enhanced: Enhanced header component for improved navigation and styling

issue: #2381[(https://github.com/keploy/keploy/issues/2381)]

Description:

This pull request updates the Header component to enhance the navbar ui by providing the dock feature.

Changes made:
Refactored the code of the header to get a better navbar as per Figma provided 

Benefits: These enhancements contribute to a more cohesive and user-friendly experience by ensuring easy navigation and an aesthetically pleasing design, encouraging users to explore the site further.

**Comment by shivamsouravjha** [comment]
please resolve the merge conflicts.

**Comment by TvisharajiK** [comment]
> Enhanced: Enhanced header component for improved navigation and styling
> 
> issue: #2381[(https://github.com/[keploy/keploy/issues/2381](https://github.com/keploy/keploy/issues/2381))]
> 
> Description:
> 
> This pull request updates the Header component to enhance the navbar ui by providing the dock feature.
> 
> Changes made: Refactored the code of the header to get a better navbar as per Figma provided
> 
> Benefits: These enhancements contribute to a more cohesive and user-friendly experience by ensuring easy navigation and an aesthetically pleasing design, encouraging users to explore the site further.

Also keep the positioning of div inside the header tag (better coding practice and readability)
Kindly change it

**Comment by Hermione2408** [comment]
closing PR since it is stale, feel free to reopen

**Pull request closed without merging**
