### PR TITLE
Add Email Check to Keploy Test Coverage Challenge

### PR DESCRIPTION
**Pull request by starvader13**
This PR aims to solve the Issue https://github.com/keploy/keploy/issues/2082

### Changes:
- [X] Implement Zod Validation to ensure the email string is not empty and is a valid email format.
- [X] Handle the rendering logic to provide a user-friendly message such as "The string entered needs to be a valid Email.."

### Screenshot:
image

**Clicking Subscribe with Random / Empty Email**
image

**Clicking Subscribe with Valid Email**
image

PS: The backend call does not occur on the local setup because of which the `input box` and `Subscribe button` are not hidden. However, it will work on production.

### CODE REVIEW

**Comment by starvader13** [comment]
@Swpn0neel This solves the issue but there are some other suggestions I want you to look at.

**Review by Swpn0neel — APPROVED** [review]
LGTM!

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @starvader13,
I see you have added email validation using zod. While zod is great for structured and complex validations, for a simple email validation, a regex function is more efficient and straightforward and consider disabling the subscribe button until the email is valid and not null you can take reference from our subscribe newsletter component -https://github.com/keploy/blog-website/blob/main/components/subscribe-newsletter.tsx

**Comment by starvader13** [comment]
> Hey @starvader13, I see you have added email validation using zod. While zod is great for structured and complex validations, for a simple email validation, a regex function is more efficient and straightforward and consider disabling the subscribe button until the email is valid and not null you can take reference from our subscribe newsletter component -https://github.com/keploy/blog-website/blob/main/components/subscribe-newsletter.tsx

@Hermione2408 The approach looks good to me, and I have made the necessary changes for email validation. Additionally, I have implemented an interactive way of displaying a `message` based on the user's input to enhance user experience. The message will now render dynamically according to the user's input, making the interface more engaging.

image
Screenshot from 2024-07-19 14-13-12
Screenshot from 2024-07-19 14-13-23

However, the `disabled` attribute integration is challenging because we use a `Link` component instead of a `Button`, and `Link` does not accept the `disabled` attribute. I tried using `aria-disabled`, but it did not work.

#### Possible Approaches:
1. **Migrate from a Link component to a Button component**.
2. **Refactor the Link component based on the email validation result**:
   - Modify the `href`
   - Modify the `onClick` event
   - Modify the `aria-disabled` attribute

**Comment by Hermione2408** [comment]
> However, the `disabled` attribute integration is challenging because we use a `Link` component instead of a `Button`, and `Link` does not accept the `disabled` attribute. I tried using `aria-disabled`, but it did not work.
> 
> #### Possible Approaches:
> 1. **Migrate from a Link component to a Button component**.
> 2. **Refactor the Link component based on the email validation result**:
>    
>    * Modify the `href`
>    * Modify the `onClick` event
>    * Modify the `aria-disabled` attribute

Thanks for the changes! The interactive message feature based on user input adds a nice touch. I get the challenge with the disabled attribute on the Link component. Let's switch it to a Button while keeping the functionality and styling the same.

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Great work!! Go ahead with changing the `Link` to `button`

**Comment by starvader13** [comment]
> Let's switch it to a Button while keeping the functionality and styling the same.

I have made the changes you asked for. However, I believe that when the button is disabled, the cursor should be set to `not-allowed`.

As far as I studied the codebase, I discovered that -

Currently, the default styles for the button are set to:
```css
button {
    cursor: pointer !important;
}
```
This does not allow me to change the cursor style of a button either through `tailwind` or `inline`:

To change the cursor to `not-allowed` when the button is disabled, we need to add a custom style:
```css
.not-allowed-button {
    cursor: not-allowed !important;
}
```
WDYT? @Hermione2408

**Comment by Aditya-eddy** [comment]
Hey @starvader13 I think that making Individual custom css is good. Because the CSS defined previously is currently applying to some button. Making the main CSS as the base case and if we want to change we can change it with custom styling!!

**Comment by starvader13** [comment]
> Making the main CSS as the base case and if we want to change we can change it with custom styling!!

I have made the changes as required, and the section looks good to me. What's your views @Hermione2408 @Aditya-eddy @Sonichigo ?

**Review by Hermione2408 — COMMENTED** [review]
Hey @starvader13 on clicking on subscribe button nothing is happening can you please check

**Comment by starvader13** [comment]
> Hey @starvader13 on clicking on the subscribe button nothing is happening can you please check

[Screencast from 22-07-24 03:16:56 PM IST.webm](https://github.com/user-attachments/assets/f2d6c440-2092-4853-bef2-b54c4c519c79)

@Hermione2408 The API call is being triggered by the action on the subscribe button click. However, since we haven't set up an API for our local build, you won't see any requests being made or the status changing.

Previously, we used a Link that redirected the page to "#0". I believe redirecting to this URL could be a good option for a button click.

**Review by Aditya-eddy — APPROVED** [review]
Yup works LGTM !!

**Review by Hermione2408 — APPROVED** [review]
Got it! build works fine LGTM

**Comment by starvader13** [comment]
> Got it! build works fine LGTM

I think then this could be merged, if no further change is required ?

**Pull request merged**
