### PR TITLE
Added preview image for landing page

### PR DESCRIPTION
**Pull request by yaten2302**
# Fixes - https://github.com/keploy/keploy/issues/1875

The preview image will be visible whenever a user shares https://keploy.io/ in a chat(like slack etc)

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 couple of issues with pr:
1. The preview image is not showing can share how did you test it? (I'll attach my screenshot)
2. Please use the seprate file for svg and then use it in app/layout.tsx.
3.If adding the preview image for slack etc. For twitter it will require twitter cards you can ref [here](https://developer.x.com/en/docs/twitter-for-websites/cards/guides/getting-started) for it.
Screenshot from 2024-06-28 13-14-05

Thanks!!

**Comment by yaten2302** [comment]
Hey @Aditya-eddy, thanks for your suggestions.
1. Actually, I didn't know how to check the social share preview, could you please guide that how you've done it, before pushing my changes, I'll thoroughly test my code.
2. Also, I've added the twitter:card as well now 👍

**Comment by Aditya-eddy** [comment]
You can use this chrome extension for viewing on facebook , X  etc
https://chromewebstore.google.com/detail/social-share-preview/ggnikicjfklimmffbkhknndafpdlabib

**Comment by yaten2302** [comment]
@Aditya-eddy now is it looking good? Earlier I added the wrong path, now I've changed that and also I've made some changes in the `logo.svg`, since the logo wasn't visible, so I changed the X-axis and the width of logo.

image

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 nice changes just some final things:
1. Can you also show for the twitter?
2. Also Can you make the logo in the center It would look good. Also please push you're code whenever you are ready!!
Thanks!!

**Comment by yaten2302** [comment]
Hey @Aditya-eddy, I've made the changes, it's now working for twitter as well 👍 I'm just pushing my changes!!

image

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 nice work!!. But in the future please use -s flag when you commit.
LGTM @Sonichigo @nehagup.

**Comment by yaten2302** [comment]
Sure @Aditya-eddy, I'll use the `-s` flag from next time onwards 👍

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 can you please resolve the conflicts in the pr?

**Comment by yaten2302** [comment]
@Aditya-eddy , could you please guide that how can I resolve the conflicts? <br>
image

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @yaten2302 good work but please replace the keploy image with this one https://github.com/keploy/website/blob/b86793aa97a0bc23ee10a720ed3ec91c749dbd71/components/ui/logo.tsx#L3
this is the same keploy logo that we are using in landing page

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 for resolving the errors:
1. add the github.com/keploy/website as upstream using `git add remote add upstream https://github.com/keploy/website/`
2. then fetch all the branch of the remote repo using `git fetch --all`
3. Then finally merge the keploy/main into your repo using `git merge upstream/main`

Then resolve the errors locally and push the changes to the main repo.

**Comment by yaten2302** [comment]
@Hermione2408 , actually, I'm having a doubt that, if we replace the current logo with the `logo.tsx` file, then will it render the it? Because it's a `tsx` file and I tried doing that, but ig it'll not be rendered?
Could you please guide regarding this?

**Comment by yaten2302** [comment]
Hey @Aditya-eddy @Hermione2408 , I've now replaced the keploy logo with the one given in the `logo.tsx` file, as suggested by @Hermione2408 . But, there's an issue, that the logo is looking like this: <br>
image

**Comment by yaten2302** [comment]
I've copied the entire logo.tsx file in the logo.svg, all I've changed is that I removed the <Link></Link> attr

**Comment by Aditya-eddy** [comment]
hey @yaten2302 can you please push the changes so that we can check?

**Comment by yaten2302** [comment]
Hey @Aditya-eddy I've now pushed my changes, could you please review those?
Also, ig I forgot to merge the conflicts, may I resolve it now or should I wait for the approval first?

**Comment by Aditya-eddy** [comment]
You can resolve it!
Also i saw that you were using logo.svg which is not similar to what we have on the main website.You can svg, xsd is not necessary.
Also please center the svg in the center. As show in picture the logo is not in center.

**Comment by yaten2302** [comment]
@Aditya-eddy , should I delete the logo.xsd file if it's not needed? Also, I copied this from the `components/ui/logo.tsx`, as suggested by Hermione2408, all I've changed is that I've removed the `<Link>...</Link>` from the logo.svg file. Could you please guide that should I keep the [previous logo](https://github.com/keploy/website/pull/49#issuecomment-2197398382) or what should I change in this one(which I just copied from logo.tsx file)?

**Comment by Aditya-eddy** [comment]
I think the svg @Hermione2408 told is good. Here is the svg file for. Please make it in center and scale is accordingly. And yes you can delete the logo.xsd. logo.svg is fine enough. Convert the txt file into svg and use accordingly.
[logo.txt](https://github.com/user-attachments/files/16230035/logo.txt)

**Comment by yaten2302** [comment]
image
<br>
@Aditya-eddy , now is it looking good?

**Comment by yaten2302** [comment]
Also, @Aditya-eddy , can I resolve the conflicts from here only(like from the website itself)? Actually, when I'm running the commands, it's not working?

**Comment by yaten2302** [comment]
I'm on the resolve conflicts page, but I'm not really sure what do I've to do here, could you please guide <br>
image

**Comment by Swpn0neel** [comment]
> Also, @Aditya-eddy , can I resolve the conflicts from here only(like from the website itself)? Actually, when I'm running the commands, it's not working?

You can't, because it will fail the DCO check!

**Comment by yaten2302** [comment]
@Swpn0neel @Aditya-eddy , I was trying to merge the changes, could you please guide that should I keep these changes or these have to be removed?<br>
image
<br>
In the browser, these are showing conflict issues: <br>
image
<br>
I've resolved these, but after this I'm not able to understand that do I've to keep the changes or remove them, could you please guide: <br>
image
image

**Comment by yaten2302** [comment]
Also, when I run the command - `git fetch --all`, then these changes also came along with the conflicting file, could you please also guide that should I commit these as well? <br>
image

**Comment by Aditya-eddy** [comment]
Hey @yaten2302 if you resolved the issue locally and want them to show in the browsers you have to then push changes.
If there are no conflicts locally. you can just push the changes by `git add .` and then `git commit -s -m ""`. Then conflicts will not show in the browsers.

**Comment by Aditya-eddy** [comment]
> Also, when I run the command - `git fetch --all`, then these changes also came along with the conflicting file, could you please also guide that should I commit these as well? image

You have to use git fetch one time only to fetch the changes from main repo. Then you will merge the changes into you local codebase. Then conflicts will occur. So you will resolve the conflicts. Then after checking locally the website is working fine and there are no conflicts only then push the changes to branch. Then you would not see any conflicts in the browsers also.

**Comment by yaten2302** [comment]
> Hey @yaten2302 if you resolved the issue locally and want them to show in the browsers you have to then push changes. If there are no conflicts locally. you can just push the changes by `git add .` and then `git commit -s -m ""`. Then conflicts will not show in the browsers.

@Aditya-eddy till now, I haven't resolved the conflicts, I'm working on it. Actually, my doubt was that these changes which you are seeing on line 85-97, I haven't added those, so I wanted to ask that should I remove these or should be kept as it is? <br>
image

**Comment by yaten2302** [comment]
> > Also, when I run the command - `git fetch --all`, then these changes also came along with the conflicting file, could you please also guide that should I commit these as well? image
> 
> You have to use git fetch one time only to fetch the changes from main repo. Then you will merge the changes into you local codebase. Then conflicts will occur. So you will resolve the conflicts. Then after checking locally the website is working fine and there are no conflicts only then push the changes to branch. Then you would not see any conflicts in the browsers also.

Yes, I've used git fetch only once and after that one time only, [these changes](https://github.com/keploy/website/pull/49#issuecomment-2232368486) were being shown. I wanted to ask here that do I've to commit these as well?

**Comment by Aditya-eddy** [comment]
> > Hey @yaten2302 if you resolved the issue locally and want them to show in the browsers you have to then push changes. If there are no conflicts locally. you can just push the changes by `git add .` and then `git commit -s -m ""`. Then conflicts will not show in the browsers.
> 
> @Aditya-eddy till now, I haven't resolved the conflicts, I'm working on it. Actually, my doubt was that these changes which you are seeing on line 85-97, I haven't added those, so I wanted to ask that should I remove these or should be kept as it is? image

yes you have to keep the script changes coming from the main keploy branch. Also yes. please commit the changes. After resolving.

**Comment by yaten2302** [comment]
@Aditya-eddy here's a screenshot of the resolved conflicts <br>
image

**Comment by Sonichigo** [comment]
@yaten2302 i have added comment's on commits regarding https://github.com/keploy/keploy/issues/2074

**Comment by yaten2302** [comment]
Got it @Sonichigo sir, I'll just fix that 👍

**Comment by yaten2302** [comment]
Made the changes @Sonichigo sir, kindly review 👍

**Comment by Aditya-eddy** [comment]
LGTM @Sonichigo @Hermione2408 .

**Review by Swpn0neel — APPROVED** [review]

**Comment by yaten2302** [comment]
@Swpn0neel sir, if this PR is approved, then may I add my name in the leaderboard?
This PR fixes 2 issues and one of the issue is under `kROC` label, level 2 - https://github.com/keploy/keploy/issues/2074. Could you also please tell the points for a level 2 issue?

**Comment by Swpn0neel** [comment]
Go ahead! It's 4

**Comment by nehagup** [comment]
This looks good @yaten2302 ! Thanks for the effort.

**Comment by yaten2302** [comment]
Thank you so much, @nehagup ma'am😀
Looking forward for more contributions 👍

**Pull request merged**
