### PR TITLE
feat: update sitemap

### PR DESCRIPTION
**Pull request by Sonichigo**

### CODE REVIEW

**Review by nehagup — COMMENTED** [review]
@Sonichigo please remove yarn lock changes as they are necessary.

**Comment by Sonichigo** [comment]
removed! 👍

**Review by nehagup — CHANGES_REQUESTED** [review]
Please remove the duplicate urls, for example https://keploy.io/docs/1.0.0/server/server-installation/ 

You can use https://www.mysitemapgenerator.com/ to validate sitemap

**Comment by Sonichigo** [comment]
Remove duplicated ones!
image

**Review by nehagup — APPROVED** [review]

**Pull request merged**
