### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by Aman172003**
Closes Issue [#2126](https://github.com/keploy/keploy/issues/2126)

Before Changes:
Screenshot 2024-07-25 at 3 08 31 PM

After Changes:
Screenshot 2024-07-25 at 3 01 09 PM

### CODE REVIEW

**Review by Aditya-eddy — APPROVED** [review]
Build Works!! LGTM!!

**Comment by Aman172003** [comment]
@Aditya-eddy review required!!

**Comment by Aditya-eddy** [comment]
Hey @Aman172003 i already reviewed it. It works fine!

**Comment by Aman172003** [comment]
@Aditya-eddy need to do anything, though the pr is not merged yet?

**Review by nehagup — APPROVED** [review]

**Pull request merged**
