### PR TITLE
added neon gradient behind the cta buttons

### LINKED ISSUE #2161: [feature]: add neon gradient behind the CTA buttons on the landing page
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Idea is to add https://magicui.design/docs/components/neon-gradient-card neon gradient effect behind the main call-to-action buttons. 

### Why should this be worked on?

better design

### Repository

keploy

### PR DESCRIPTION
**Pull request by Harshjosh361**
fix : [#2161](https://github.com/keploy/keploy/issues/2161)
Added neon gradient behind buttons from Magic UI library

### CODE REVIEW

**Comment by Harshjosh361** [comment]
https://github.com/user-attachments/assets/8564fcaf-797b-42a8-a676-7ad51ed091bb

**Comment by Harshjosh361** [comment]
image

**Review by khareyash05 — APPROVED** [review]
LGTM!

**Comment by khareyash05** [comment]
Suggestion- Create a new branch on your fork, instead of doing changes on the main

This will ensure the changed made on main doesnt affect your changes later while creating a PR, lesser merge conflicts

**Comment by Harshjosh361** [comment]
Thank you for the advice and merging the issue! I’ll use a new branch in my fork for future changes to avoid conflicts.

**Comment by Harshjosh361** [comment]
@khareyash05 @Swpn0neel can u please add the label to the merged pr as hacktoberfest-accepted

**Pull request merged**
