### PR TITLE
Fix Responsive Issue: Collaboration Section Overlaps with GIFs on Mobile

### LINKED ISSUE #2114: Responsive Issue in Mobile Version - Collaboration Section Overlaps with GIFs
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
In the mobile version of the website, the recent collaboration part goes behind the GIFs used in the feature section. This makes the collaboration part unreadable and affects the user experience.

## Expected Behavior
The collaboration part should be visible and not overlap with the GIFs.

## Actual Behavior
The collaboration part goes behind the GIFs, making it unreadable.

## Screenshots

for more understanding of the issue Please have a look at the Screenshots which I attached below:-

### In mobile Versio:-

Screenshot 2024-07-22 093555

### In Laptop Version:-
Screenshot 2024-07-22 100123

## Steps to Reproduce

1. Open the website on a mobile device.
2. Navigate to the feature section.
3. Observe that the recent collaboration part overlaps with the GIFs.

None

### Repository

keploy/website

### PR DESCRIPTION
**Pull request by siddharthbaleja7**
### Description
This PR addresses a responsive design issue in the mobile version of the website where the collaboration section was overlapping with GIFs. The problem occurred due to improper layout handling on smaller screens.
#### Before Fix
![Before Fix]
Screenshot 2024-07-26 at 15 32 51

#### After Fix
![After Fix] 
Screenshot 2024-07-26 at 15 33 04

### Testing
- Tested the website on various mobile devices to confirm that the collaboration section no longer overlaps with GIFs.
- Ensured that no other layout issues were introduced by the changes.

### Related Issues
- Fixes #2114

### Additional Notes
- If any additional testing is required or if further adjustments are needed, please let me know.

### CODE REVIEW

**Review by Swpn0neel — APPROVED** [review]
That's not how we use Tailwind classes. I think you might be unfamiliar with Tailwind, so it's better if you can check its documentation or something!

**Comment by Aditya-eddy** [comment]
Hey @siddharthbaleja7 still overlapping:
image

**Comment by Sonichigo** [comment]
@siddharthbaleja7 any updates ?

**Comment by nehagup** [comment]
Closing since this is stale. Please feel free to reopen with changes.

**Pull request closed without merging**
