### PR TITLE
refactor: minor bugs and add global routes and increase font size of carousel

### LINKED ISSUE #1695: [bug]: increase size of carousel items as well as the font size
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Going through the carousel seems overwhelming and increasing the font size of the same would be great. It would make it more readable 

### Steps to reproduce

image

### Environment

None

### Version

Local

### Repository

website

### PR DESCRIPTION
**Pull request by khareyash05**
Minor console errors while setting up the website and used Image from `next/image` and add global routes for images so they are readable and easily accesible even when hosted

Fixes [https://github.com/keploy/keploy/issues/1695](https://github.com/keploy/keploy/issues/1695)

### CODE REVIEW

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @khareyash05, 
- seems like blur effect is missing on side of carousel now  
- please keep the size same on small screen, looks too big in that 
- Also check the warnings in console once for image component

**Comment by khareyash05** [comment]
> Hey @khareyash05,
> 
> * seems like blur effect is missing on side of carousel now
> * please keep the size same on small screen, looks too big in that
> * Also check the warnings in console once for image component

Hey Thank you for the detailed review. I solved the first issue but I am not able to locate the line for scrollbar on the smaller screen size. Could you please help me with that. Thanks

**Comment by Hermione2408** [comment]
> > Hey @khareyash05,
> > 
> > * seems like blur effect is missing on side of carousel now
> > * please keep the size same on small screen, looks too big in that
> > * Also check the warnings in console once for image component
> 
> Hey Thank you for the detailed review. I solved the first issue but I am not able to locate the line for scrollbar on the smaller screen size. Could you please help me with that. Thanks

Hey @khareyash05  I was referring to the carousel image size that you increased you can keep it same as original for the smaller screen size

**Comment by khareyash05** [comment]
> > > Hey @khareyash05,
> > > 
> > > * seems like blur effect is missing on side of carousel now
> > > * please keep the size same on small screen, looks too big in that
> > > * Also check the warnings in console once for image component
> > 
> > 
> > Hey Thank you for the detailed review. I solved the first issue but I am not able to locate the line for scrollbar on the smaller screen size. Could you please help me with that. Thanks
> 
> Hey @khareyash05 I was referring to the carousel image size that you increased you can keep it same as original for the smaller screen size

Yeah I got that. I wasnt able to locate the smaller screen sidebar code. If you could help with that. Thanks

**Comment by Hermione2408** [comment]
Hey @khareyash05  for sidebar code in mobile-view you can refer to this -https://github.com/keploy/website/blob/52cb2ce6f1b0e97742ac1925fd1c6c0aa023c37c/components/ui/mobile-menu.tsx#L12

**Comment by khareyash05** [comment]
> Hey @khareyash05 for sidebar code in mobile-view you can refer to this -
> 
> https://github.com/keploy/website/blob/52cb2ce6f1b0e97742ac1925fd1c6c0aa023c37c/components/ui/mobile-menu.tsx#L12

Thanks a lot.

**Comment by nehagup** [comment]
@khareyash05 are you still working on this?

**Comment by khareyash05** [comment]
Yes sorry for the delay. Will be submitting the edit by this week.

**Comment by nehagup** [comment]
@khareyash05 closing this PR as it's inactive. Please feel free to re-open once you make progress.

**Pull request closed without merging**
