### PR TITLE
feature: sticky banner

### PR DESCRIPTION
**Pull request by sakethreddy21**
feat: Added a sticky banner with VS Code CTA

issue: [2382](https://github.com/keploy/keploy/issues/2382)

- Created `banner.tsx` component to display a sticky banner at the bottom
- Includes Keploy logo, CTA for VS Code extension, and a close button
- Styled according to Keploy brand guidelines

### CODE REVIEW

**Comment by sakethreddy21** [comment]
image
image

**Comment by wasifkareem** [comment]
Hi @saketh-trainingmug , you literally copied my design , why would you do that😄.this issue was assigned to me and I already created [PR](https://github.com/keploy/website/pull/101) for this hours before you

**Comment by sakethreddy21** [comment]
no @wasifkareem I got this issue  as an internship task so I think I should be completing all these issues to get the interview call no I didn't copy the design but I have used your images

**Comment by wasifkareem** [comment]
> I got this issue as an internship task

I also got this as internship task, I'm [assigned](https://github.com/keploy/keploy/issues/2383) to this task by  @TvisharajiK . I have opened the [PR](https://github.com/keploy/website/pull/101) hours before you and you LITERALLY COPIED MY DESIGN. lol

**Comment by Hermione2408** [comment]
Thanks for the PR! This issue was resolved by another PR, so closing this. Appreciate your work on this!

**Pull request closed without merging**
