### PR TITLE
Adding the dark mode

### PR DESCRIPTION
**Pull request by HasanZaigam**
I updated the feature of dark Mode on the keploy website,
here are its views SS;

Screenshot 2024-07-19 154916
Screenshot 2024-07-19 155033
Screenshot 2024-07-19 155053

### CODE REVIEW

**Comment by HasanZaigam** [comment]
Hasan Zaigam who makes the above PR.
I facing the DCO problem please help me to fix it

**Comment by nehagup** [comment]
@HasanZaigam this is a great initiative! To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~1 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin new_branch

**Comment by HasanZaigam** [comment]
@nehagup  thanks for helping

**Comment by HasanZaigam** [comment]
you are participating in Flipkart Grid 6.0 ?

**Pull request closed without merging**
