### PR TITLE
Adding the dark mode to the website

### PR DESCRIPTION
**Pull request by HasanZaigam**
I successfully added the dark mode to the websites and here are the SS:-
Screenshot 2024-07-19 154916
Screenshot 2024-07-19 155033
Screenshot 2024-07-19 155053

### CODE REVIEW

**Review by Aditya-eddy — CHANGES_REQUESTED** [review]
Hey @HasanZaigam thanks for the pr. Multiple issues to be dealt here with:
1. I think you should search for more good icons for dark and light mode.
2. The heading is missing text on top. Please visit the main website to check for it.
3. Also the components needs to be changed as we. Currently switching just the background to dark mode is not looking good. I'll attach the screenshot where the color contrasting is not working.
Screenshot from 2024-07-20 06-03-23
Screenshot from 2024-07-20 06-03-10
Screenshot from 2024-07-20 06-03-00

**Comment by HasanZaigam** [comment]
ok, there is no problem, I will change it, but the problem that came here was basically the problem that I tried to change the colour of the components that you highlighted here, but I was confused about what should be the colour coding scheme. that's why I didn't change them. If you have any suggestion as to what will be their colour in dark Mode. Please suggest.

**Comment by HasanZaigam** [comment]
@Aditya-eddy I make the changes that you asked for. Please review the PR again. Here's a list of all the changes I made:

### 1. Change the UI design of the Dark Mode Toggle Button to make it more visually appealing to users.

Screenshot 2024-07-21 112523
Screenshot 2024-07-21 112542

### 2. Also makes changes in the keploy Bunny Community.

Screenshot 2024-07-21 112608

### 3. Makes changes in the Problem-solving Section in the dark mode time.

Screenshot 2024-07-21 112625

### 4. Also made changes in the tweeter Testimonials part for the dark Mode.

Screenshot 2024-07-21 112636

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @HasanZaigam ,Thanks for the PR. There are still multiple changes required, as mentioned previously by @Aditya-eddy. Here are some key points to address:

- The current color scheme is not very suitable. Please explore some dark mode websites for inspiration. You can also check out the MUI color palette: https://mui.com/material-ui/customization/palette/, Material Design's color tool.
- Text Contrasting is crucial, use lighter colors such as white or light gray for text to maintain legibility against the dark background
- Your changes have affected the existing light mode I'll attach screenshots below. It’s crucial that the light mode remains unaffected and functions as expected while implementing dark mode.

Also while building this warning is coming please check -
```
(node:29682) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
Screenshot 2024-07-22 at 1 33 46 PM
Screenshot 2024-07-22 at 1 34 00 PM

**Comment by HasanZaigam** [comment]
## I fixed all the changes that affected the light mode. You can see this:-
Screenshot 2024-07-22 225954

## I also try to fix the building error. Now only the Hydration error is showing and it will not show when you deploy the website to the User.
Screenshot:-
Screenshot 2024-07-22 223846

## I have addressed all the mentioned error points, but I apologize for being unable to fix the error in the language section in dark mode. I cannot find a way to change the marquee language animation blocks because some of the languages inside the boxes are not visible in dark mode. I am referring to this issue:

image

### Please guide me in fixing this issue also.
@Hermione2408 
@Aditya-eddy

**Review by harshsbhat — COMMENTED** [review]
I think you can take inspiration from keploy/docs for the dark mode. Refer that for the icons and color pallete.

**Comment by HasanZaigam** [comment]
thanks @harshsbhat for your invaluable advice and suggestion

**Comment by Swpn0neel** [comment]
To pass the DCO check, you can do this:
- Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
- In your local branch, run: git rebase HEAD~9 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin new_branch

**Review by Aditya-eddy — CHANGES_REQUESTED** [review]
Hey @HasanZaigam currently you can leave the marquee boxes first lets work on the background and the Text.
1. On the top in the light mode you have changed how the main Heading's second line looks. Earlier it was gradient but now it's just plain orange please fix that.
2. For  the background you can try using the neutral pallete which is already defined in the tailwind config file. Try to make it as plain as possible. For example currently in your dark mode twitter section. It has a very light border which does'nt look whereas a darker gray color would look nice. So try to do this with every component.
3. For more reference to how you can show the language widget below the marquee boxes or in the center of the main sharing section more effectively . You can can check the keploy docs website.
4. Also in the light mode make the button's background as white as we don't want to make it stand out more that the CTA. Also please make the icon's background as same as the header.

Thanks!!

**Comment by HasanZaigam** [comment]
Ok and Thanks @Aditya-eddy for your review and advice, I will start correcting it one by one and after all the corrections I let you know about it.

**Comment by HasanZaigam** [comment]
> Hey @HasanZaigam currently you can leave the marquee boxes first lets work on the background and the Text.
> 
> 1. On the top in the light mode you have changed how the main Heading's second line looks. Earlier it was gradient but now it's just plain orange please fix that.
> 2. For  the background you can try using the neutral pallete which is already defined in the tailwind config file. Try to make it as plain as possible. For example currently in your dark mode twitter section. It has a very light border which does'nt look whereas a darker gray color would look nice. So try to do this with every component.
> 3. For more reference to how you can show the language widget below the marquee boxes or in the center of the main sharing section more effectively . You can can check the keploy docs website.
> 4. Also in the light mode make the button's background as white as we don't want to make it stand out more that the CTA. Also please make the icon's background as same as the header.
> 
> Thanks!!

Hii @Aditya-eddy I fix the error that you are mentioned above please check it and let me know if further changes needed

**Comment by Aditya-eddy** [comment]
Hey @HasanZaigam still some things left unimplemented from the above points.
1. Background need to be like keploy docs website have in the dark mode. It's currently pitch back.
2. The icons should now have a bg color. In light mode we have that orange background which does not looks nice. Try to take the inspiration from the docs website.
3.The footer needs to change color as well. You can refer keploy docs website.
4. Also for the twitter bubbles it should have a lighter background . Currently background color of website and and it twitter is mixing in.
Thanks!!

**Comment by HasanZaigam** [comment]
ok @Aditya-eddy I will try updated the all the changes that you mentioned above.

**Comment by nehagup** [comment]
Closing since this is stale. Please feel free to reopen with changes.

**Pull request closed without merging**
